# Generated by Django 5.2 on 2025-09-26 13:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReservaFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_participantes_confirmados', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de participantes confirmados')),
            ],
            options={
                'verbose_name': 'Detalle Reserva Físico',
                'verbose_name_plural': 'Detalles de Reservas Físicas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p00_solicitante', models.CharField(max_length=100)),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('email_solicitante', models.EmailField(max_length=254)),
                ('telefono_solicitante', models.CharField(max_length=100)),
                ('vicepresidencia_solicitante', models.CharField(max_length=100)),
                ('gerencia_solicitante', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], default='presencial', max_length=10)),
                ('tipo_solicitud', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa')], default='interna', max_length=10)),
                ('fecha_uso', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('motivo', models.TextField(verbose_name='Motivo de reserva')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('mensaje_aprobar_rechazar', models.TextField(blank=True, default='', null=True, verbose_name='Mensaje de aprobación/rechazo/cancelación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cambio de estado')),
                ('requerimientos', models.JSONField(blank=True, default=list, null=True, verbose_name='Requerimientos')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_uso', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_participantes', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de participantes')),
            ],
            options={
                'verbose_name': 'Reserva Espacio',
                'verbose_name_plural': 'Reservas Espacios',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReservaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfitrion_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('espacio_transmision', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_transmision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_digitales', to='core.ubicacion')),
            ],
            options={
                'verbose_name': 'Detalle Reserva Digital',
                'verbose_name_plural': 'Detalles de Reservas Digitales',
                'ordering': ['-reserva_espacio__reserva__fecha_uso', 'reserva_espacio__reserva__hora_inicio'],
            },
        ),
    ]
