# Generated by Django 5.2 on 2025-09-26 13:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_espacios', to='espacios.espacio'),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_espacios', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacios',
            field=models.ManyToManyField(related_name='reservas', through='reservas.ReservaEspacio', to='espacios.espacio'),
        ),
        migrations.AddField(
            model_name='detallereservafisico',
            name='reserva_espacio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_fisico', to='reservas.reservaespacio'),
        ),
        migrations.AddField(
            model_name='detallereservadigital',
            name='reserva_espacio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_digital', to='reservas.reservaespacio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.tipoactividad'),
        ),
        migrations.AddConstraint(
            model_name='reservaespacio',
            constraint=models.UniqueConstraint(fields=('reserva', 'espacio'), name='uniq_reserva_espacio', violation_error_message='Ya existe una reserva para este espacio.'),
        ),
        migrations.AddIndex(
            model_name='detallereservafisico',
            index=models.Index(fields=['reserva_espacio'], name='reservas_de_reserva_a0b21d_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallereservafisico',
            constraint=models.UniqueConstraint(fields=('reserva_espacio',), name='uniq_reserva_fisico', violation_error_message='Ya existe un detalle de reserva físico para esta reserva.'),
        ),
        migrations.AddIndex(
            model_name='detallereservadigital',
            index=models.Index(fields=['reserva_espacio'], name='reservas_de_reserva_459c46_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallereservadigital',
            constraint=models.UniqueConstraint(fields=('reserva_espacio',), name='uniq_reserva_digital', violation_error_message='Ya existe un detalle de reserva digital para esta reserva.'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_uso'], name='reservas_re_fecha_u_8c08ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='check_hora_inicio_menor_fin', violation_error_message='La hora de inicio debe ser menor a la hora de fin.'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__gte', datetime.time(8, 0)), ('hora_fin__lte', datetime.time(22, 0))), name='check_hora_inicio_menor_fin_8am_10pm', violation_error_message='Solo se permite reservar entre las 8:00 AM y las 10:00 PM.'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_uso__gte', datetime.date(2025, 9, 26))), name='check_fecha_uso_futuro_o_hoy', violation_error_message='La fecha de uso debe ser hoy o en el futuro.'),
        ),
    ]
