# Generated by Django 5.2 on 2025-09-26 13:40

import apps.espacios.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9 ]*', message='El nombre del espacio debe comenzar con una letra, y solo puede contener letras, números y espacios.')])),
                ('capacidad_maxima', models.PositiveSmallIntegerField(help_text='Capacidad máxima (≤ 5000)', validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['tipo'], name='espacios_es_tipo_48984b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidad_maxima__lte', 5000)), name='check_capacidad_max_5000')],
            },
        ),
        migrations.CreateModel(
            name='DetalleEspacioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.PositiveSmallIntegerField(help_text='Piso en que se encuentra el espacio (≤ 40)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('tipo', models.CharField(choices=[('salon', 'Salón'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio'), ('otro', 'Otro')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.espacios.models.user_directory_path)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_fisicos', to='core.ubicacion')),
                ('espacio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_fisico', to='espacios.espacio')),
            ],
            options={
                'verbose_name': 'Detalle Espacio Físico',
                'verbose_name_plural': 'Detalles de Espacios Físicos',
                'constraints': [models.UniqueConstraint(fields=('espacio',), name='uniq_espacio_fisico', violation_error_message='Ya existe un detalle de espacio físico para este espacio.')],
            },
        ),
        migrations.CreateModel(
            name='DetalleEspacioDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL del espacio digital', null=True)),
                ('plataforma', models.ForeignKey(help_text='Plataforma del espacio digital', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.plataformadigital')),
                ('espacio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_digital', to='espacios.espacio')),
            ],
            options={
                'verbose_name': 'Detalle Espacio Digital',
                'verbose_name_plural': 'Detalles de Espacios Digitales',
                'constraints': [models.UniqueConstraint(fields=('espacio',), name='uniq_espacio_digital', violation_error_message='Ya existe un detalle de espacio digital para este espacio.')],
            },
        ),
    ]
