# Generated by Django 5.2 on 2025-09-26 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9 ]*', message='El nombre del espacio debe comenzar con una letra, y solo puede contener letras, números y espacios.')]),
        ),
    ]
